/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crossChainReceiverSol from "./CrossChainReceiver.sol";
export type { crossChainReceiverSol };
import type * as swapTestnetUsdcSol from "./SwapTestnetUSDC.sol";
export type { swapTestnetUsdcSol };
export type { MockUSDC } from "./MockUSDC";
export type { TransferUSDC } from "./TransferUSDC";
