/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISwapTestnetUSDC,
  ISwapTestnetUSDCInterface,
} from "../../../contracts/CrossChainReceiver.sol/ISwapTestnetUSDC";

const _abi = [
  {
    inputs: [],
    name: "getSupportedTokens",
    outputs: [
      {
        internalType: "address",
        name: "usdcToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "compoundUsdcToken",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "swap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISwapTestnetUSDC__factory {
  static readonly abi = _abi;
  static createInterface(): ISwapTestnetUSDCInterface {
    return new utils.Interface(_abi) as ISwapTestnetUSDCInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISwapTestnetUSDC {
    return new Contract(address, _abi, signerOrProvider) as ISwapTestnetUSDC;
  }
}
