/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFauceteer,
  IFauceteerInterface,
} from "../../../contracts/SwapTestnetUSDC.sol/IFauceteer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "drip",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFauceteer__factory {
  static readonly abi = _abi;
  static createInterface(): IFauceteerInterface {
    return new utils.Interface(_abi) as IFauceteerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFauceteer {
    return new Contract(address, _abi, signerOrProvider) as IFauceteer;
  }
}
