/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFauceteer__factory } from "./IFauceteer__factory";
export { SwapTestnetUSDC__factory } from "./SwapTestnetUSDC__factory";
