/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../../../../common";
import type {
  CallWithExactGas,
  CallWithExactGasInterface,
} from "../../../../../../../@chainlink/contracts-ccip/src/v0.8/shared/call/CallWithExactGas";

const _abi = [
  {
    inputs: [],
    name: "NoContract",
    type: "error",
  },
  {
    inputs: [],
    name: "NoGasForCallExactCheck",
    type: "error",
  },
  {
    inputs: [],
    name: "NotEnoughGasForCall",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220c756f585f4627896ce587f3c5c949dd8b4edf6d296236fae18072a204546da5f64736f6c63430008140033";

type CallWithExactGasConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CallWithExactGasConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CallWithExactGas__factory extends ContractFactory {
  constructor(...args: CallWithExactGasConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<CallWithExactGas> {
    return super.deploy(overrides || {}) as Promise<CallWithExactGas>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): CallWithExactGas {
    return super.attach(address) as CallWithExactGas;
  }
  override connect(signer: Signer): CallWithExactGas__factory {
    return super.connect(signer) as CallWithExactGas__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CallWithExactGasInterface {
    return new utils.Interface(_abi) as CallWithExactGasInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CallWithExactGas {
    return new Contract(address, _abi, signerOrProvider) as CallWithExactGas;
  }
}
